
 Network yanpitangui-dotnet-v2_backend  Creating
 Network yanpitangui-dotnet-v2_backend  Created
 Volume "yanpitangui-dotnet-v2_postgres-socket"  Creating
 Volume "yanpitangui-dotnet-v2_postgres-socket"  Created
 Volume "yanpitangui-dotnet-v2_uds-sockets"  Creating
 Volume "yanpitangui-dotnet-v2_uds-sockets"  Created
 Container yanpitangui-dotnet-v2-rinha-db-1  Creating
 Container yanpitangui-dotnet-v2-nats-1  Creating
 Container yanpitangui-dotnet-v2-nats-1  Created
 Container yanpitangui-dotnet-v2-rinha-db-1  Created
 Container yanpitangui-dotnet-v2-worker-1  Creating
 Container backend-2  Creating
 Container backend-1  Creating
 Container backend-2  Created
 Container yanpitangui-dotnet-v2-worker-1  Created
 Container backend-1  Created
 Container yanpitangui-dotnet-v2-nginx-1  Creating
 Container yanpitangui-dotnet-v2-nginx-1  Created
Attaching to backend-1, backend-2, nats-1, nginx-1, rinha-db-1, worker-1
nats-1  | [1] 2025/08/16 16:10:50.976458 [INF] Starting nats-server
nats-1  | [1] 2025/08/16 16:10:50.976503 [INF]   Version:  2.11.7
nats-1  | [1] 2025/08/16 16:10:50.976505 [INF]   Git:      [df44964]
nats-1  | [1] 2025/08/16 16:10:50.976507 [INF]   Cluster:  my_cluster
nats-1  | [1] 2025/08/16 16:10:50.976509 [INF]   Name:     NA3LAOM5YYUNSACRVSYQDRBAWOEBZKWSYJKVYBG3UAXVV3RCPCCEVUJW
nats-1  | [1] 2025/08/16 16:10:50.976516 [INF]   ID:       NA3LAOM5YYUNSACRVSYQDRBAWOEBZKWSYJKVYBG3UAXVV3RCPCCEVUJW
nats-1  | [1] 2025/08/16 16:10:50.976527 [INF] Using configuration file: /etc/nats/nats-server.conf (sha256:c7aaa34d64beb74e7c700fd3504b40b01deb1275f6567fb81ed3809ff03a5fe4)
nats-1  | [1] 2025/08/16 16:10:50.977275 [INF] Starting http monitor on 0.0.0.0:8222
nats-1  | [1] 2025/08/16 16:10:50.977445 [INF] Listening for client connections on 0.0.0.0:4222
nats-1  | [1] 2025/08/16 16:10:51.057686 [INF] Server is ready
nats-1  | [1] 2025/08/16 16:10:51.057797 [INF] Cluster name is my_cluster
nats-1  | [1] 2025/08/16 16:10:51.058054 [INF] Listening for route connections on 0.0.0.0:6222
rinha-db-1  | The files belonging to this database system will be owned by user "postgres".
rinha-db-1  | This user must also own the server process.
rinha-db-1  | 
rinha-db-1  | The database cluster will be initialized with locale "en_US.utf8".
rinha-db-1  | The default database encoding has accordingly been set to "UTF8".
rinha-db-1  | The default text search configuration will be set to "english".
rinha-db-1  | 
rinha-db-1  | Data page checksums are disabled.
rinha-db-1  | 
rinha-db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinha-db-1  | creating subdirectories ... ok
rinha-db-1  | selecting dynamic shared memory implementation ... posix
rinha-db-1  | selecting default "max_connections" ... 100
rinha-db-1  | selecting default "shared_buffers" ... 128MB
rinha-db-1  | selecting default time zone ... Etc/UTC
rinha-db-1  | creating configuration files ... ok
rinha-db-1  | running bootstrap script ... ok
rinha-db-1  | performing post-bootstrap initialization ... ok
rinha-db-1  | initdb: warning: enabling "trust" authentication for local connections
rinha-db-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinha-db-1  | syncing data to disk ... ok
rinha-db-1  | 
rinha-db-1  | 
rinha-db-1  | Success. You can now start the database server using:
rinha-db-1  | 
rinha-db-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinha-db-1  | 
rinha-db-1  | waiting for server to start....2025-08-16 16:11:01.619 UTC [57] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
rinha-db-1  | 2025-08-16 16:11:01.623 UTC [57] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-db-1  | 2025-08-16 16:11:01.711 UTC [60] LOG:  database system was shut down at 2025-08-16 16:11:01 UTC
rinha-db-1  | 2025-08-16 16:11:01.718 UTC [57] LOG:  database system is ready to accept connections
rinha-db-1  |  done
rinha-db-1  | server started
rinha-db-1  | 2025-08-16 16:11:02.916 UTC [75] FATAL:  database "rinha" does not exist
rinha-db-1  | CREATE DATABASE
rinha-db-1  | 
rinha-db-1  | 
rinha-db-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
backend-1   | backend-1
backend-2   | backend-2
nginx-1     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1     | /docker-entrypoint.sh: Configuration complete; ready for start up
worker-1    | PoolConfig { RouterPoolSize = 3 }
worker-1    | PipelineConfig { HandlePaymentParallelism = 20, PersistPaymentsParallelism = 10, GroupSize = 100, Timeout = 10 }
rinha-db-1  | 2025-08-16 16:11:04.616 UTC [78] ERROR:  relation "payments" does not exist at character 159
rinha-db-1  | 2025-08-16 16:11:04.616 UTC [78] STATEMENT:  
rinha-db-1  | 	                SELECT processor,
rinha-db-1  | 	                       COUNT(*) AS total_requests,
rinha-db-1  | 	                       SUM(amount) AS total_amount
rinha-db-1  | 	                FROM payments
rinha-db-1  | 	                WHERE ($1 IS NULL OR requested_at >= $1)
rinha-db-1  | 	                  AND ($2 IS NULL OR requested_at <= $2)
rinha-db-1  | 	                GROUP BY processor
rinha-db-1  | 2025-08-16 16:11:04.616 UTC [78] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [83] ERROR:  relation "payments" does not exist at character 159
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [83] STATEMENT:  
rinha-db-1  | 	                SELECT processor,
rinha-db-1  | 	                       COUNT(*) AS total_requests,
rinha-db-1  | 	                       SUM(amount) AS total_amount
rinha-db-1  | 	                FROM payments
rinha-db-1  | 	                WHERE ($1 IS NULL OR requested_at >= $1)
rinha-db-1  | 	                  AND ($2 IS NULL OR requested_at <= $2)
rinha-db-1  | 	                GROUP BY processor
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [78] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [78] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [78] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [83] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [83] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [83] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.617 UTC [78] ERROR:  prepared statement "_auto0" does not exist
backend-1   | Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "payments" does not exist
backend-1   | 
backend-1   | POSITION: 159
backend-1   |    at Npgsql.Internal.NpgsqlConnector.<ReadMessageLong>d__235.MoveNext() + 0xc43
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16) + 0x50
backend-1   |    at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext() + 0x1b6d
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext() + 0x24ba
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Npgsql.NpgsqlCommand.<ExecuteReader>d__120.MoveNext() + 0xf38
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Npgsql.NpgsqlCommand.<ExecuteReader>d__120.MoveNext() + 0x1120
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderAsync>d__113.MoveNext() + 0x196
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Dapper.Internal.AsyncQueryState.<ExecuteReaderAsync>d__8.MoveNext() + 0x1ce
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Dapper.Command`1.<QueryBufferedAsync>d__63`1.MoveNext() + 0x67d
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Dapper.Command`1.<QueryBufferedAsync>d__63`1.MoveNext() + 0xc45
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Dapper.DapperAotExtensions.<AsEnumerableAsync>d__1`1.MoveNext() + 0xcc
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Program.<>c__DisplayClass0_0.<<<Main>$>b__9>d.MoveNext() + 0x3df
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Program.<>c__DisplayClass0_0.<<<Main>$>b__9>d.MoveNext() + 0x5d0
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Program.<<Main>$>d__0.MoveNext() + 0x61e
backend-1   | --- End of stack trace from previous location ---
backend-1   |    at Program.<Main>(String[] args) + 0x26
backend-1   |   Exception data:
backend-1   |     Severity: ERROR
backend-1   |     SqlState: 42P01
backend-1   |     MessageText: relation "payments" does not exist
backend-1   |     Position: 159
backend-1   |     File: parse_relation.c
backend-1   |     Line: 1449
backend-1   |     Routine: parserOpenTable
rinha-db-1  | 2025-08-16 16:11:04.714 UTC [84] ERROR:  relation "payments" does not exist at character 159
rinha-db-1  | 2025-08-16 16:11:04.714 UTC [84] STATEMENT:  
rinha-db-1  | 	                SELECT processor,
rinha-db-1  | 	                       COUNT(*) AS total_requests,
rinha-db-1  | 	                       SUM(amount) AS total_amount
rinha-db-1  | 	                FROM payments
rinha-db-1  | 	                WHERE ($1 IS NULL OR requested_at >= $1)
rinha-db-1  | 	                  AND ($2 IS NULL OR requested_at <= $2)
rinha-db-1  | 	                GROUP BY processor
rinha-db-1  | 2025-08-16 16:11:04.714 UTC [84] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  relation "payments" does not exist at character 159
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] STATEMENT:  
rinha-db-1  | 	                SELECT processor,
rinha-db-1  | 	                       COUNT(*) AS total_requests,
rinha-db-1  | 	                       SUM(amount) AS total_amount
rinha-db-1  | 	                FROM payments
rinha-db-1  | 	                WHERE ($1 IS NULL OR requested_at >= $1)
rinha-db-1  | 	                  AND ($2 IS NULL OR requested_at <= $2)
rinha-db-1  | 	                GROUP BY processor
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | 2025-08-16 16:11:04.715 UTC [80] ERROR:  prepared statement "_auto0" does not exist
rinha-db-1  | CREATE TABLE
rinha-db-1  | 2025-08-16 16:11:04.716 UTC [84] ERROR:  prepared statement "_auto0" does not exist
backend-2   | Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "payments" does not exist
backend-2   | 
backend-2   | POSITION: 159
backend-2   |    at Npgsql.Internal.NpgsqlConnector.<ReadMessageLong>d__235.MoveNext() + 0xc43
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16) + 0x50
backend-2   |    at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext() + 0x1b6d
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Npgsql.NpgsqlDataReader.<NextResult>d__52.MoveNext() + 0x24ba
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Npgsql.NpgsqlCommand.<ExecuteReader>d__120.MoveNext() + 0xf38
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Npgsql.NpgsqlCommand.<ExecuteReader>d__120.MoveNext() + 0x1120
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderAsync>d__113.MoveNext() + 0x196
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Dapper.Internal.AsyncQueryState.<ExecuteReaderAsync>d__8.MoveNext() + 0x1ce
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Dapper.Command`1.<QueryBufferedAsync>d__63`1.MoveNext() + 0x67d
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Dapper.Command`1.<QueryBufferedAsync>d__63`1.MoveNext() + 0xc45
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Dapper.DapperAotExtensions.<AsEnumerableAsync>d__1`1.MoveNext() + 0xcc
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Program.<>c__DisplayClass0_0.<<<Main>$>b__9>d.MoveNext() + 0x3df
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Program.<>c__DisplayClass0_0.<<<Main>$>b__9>d.MoveNext() + 0x5d0
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Program.<<Main>$>d__0.MoveNext() + 0x61e
backend-2   | --- End of stack trace from previous location ---
backend-2   |    at Program.<Main>(String[] args) + 0x26
backend-2   |   Exception data:
backend-2   |     Severity: ERROR
backend-2   |     SqlState: 42P01
backend-2   |     MessageText: relation "payments" does not exist
backend-2   |     Position: 159
backend-2   |     File: parse_relation.c
backend-2   |     Line: 1449
backend-2   |     Routine: parserOpenTable
rinha-db-1  | CREATE INDEX
rinha-db-1  | 
rinha-db-1  | 
rinha-db-1  | 2025-08-16 16:11:05.015 UTC [57] LOG:  received fast shutdown request
rinha-db-1  | waiting for server to shut down....2025-08-16 16:11:05.019 UTC [57] LOG:  aborting any active transactions
rinha-db-1  | 2025-08-16 16:11:05.019 UTC [84] FATAL:  terminating connection due to administrator command
rinha-db-1  | 2025-08-16 16:11:05.019 UTC [82] FATAL:  terminating connection due to administrator command
rinha-db-1  | 2025-08-16 16:11:05.019 UTC [81] FATAL:  terminating connection due to administrator command
rinha-db-1  | 2025-08-16 16:11:05.019 UTC [80] FATAL:  terminating connection due to administrator command
rinha-db-1  | 2025-08-16 16:11:05.020 UTC [79] FATAL:  terminating connection due to administrator command
[Kbackend-1 exited with code 139
nginx-1     | 2025/08/16 16:11:05 [crit] 30#30: *1 connect() to unix:/sockets/backend-1.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-1.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:05 [crit] 30#30: *1 connect() to unix:/sockets/backend-2.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-2.sock:/payments-summary", host: "localhost:9999"
rinha-db-1  | 2025-08-16 16:11:05.210 UTC [57] LOG:  background worker "logical replication launcher" (PID 63) exited with exit code 1
[Kbackend-2 exited with code 139
rinha-db-1  | 2025-08-16 16:11:05.311 UTC [58] LOG:  shutting down
rinha-db-1  | 2025-08-16 16:11:05.316 UTC [58] LOG:  checkpoint starting: shutdown immediate
rinha-db-1  | 2025-08-16 16:11:05.441 UTC [58] LOG:  checkpoint complete: wrote 927 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.110 s, sync=0.008 s, total=0.131 s; sync files=311, longest=0.003 s, average=0.001 s; distance=4277 kB, estimate=4277 kB; lsn=0/191AF38, redo lsn=0/191AF38
rinha-db-1  | 2025-08-16 16:11:05.517 UTC [57] LOG:  database system is shut down
rinha-db-1  |  done
rinha-db-1  | server stopped
rinha-db-1  | 
rinha-db-1  | PostgreSQL init process complete; ready for start up.
rinha-db-1  | 
rinha-db-1  | 2025-08-16 16:11:05.726 UTC [1] LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg130+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
rinha-db-1  | 2025-08-16 16:11:05.727 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rinha-db-1  | 2025-08-16 16:11:05.727 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rinha-db-1  | 2025-08-16 16:11:05.816 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-db-1  | 2025-08-16 16:11:05.825 UTC [93] LOG:  database system was shut down at 2025-08-16 16:11:05 UTC
rinha-db-1  | 2025-08-16 16:11:05.833 UTC [1] LOG:  database system is ready to accept connections
nginx-1     | 2025/08/16 16:11:10 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:15 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:20 [crit] 30#30: *6 connect() to unix:/sockets/backend-2.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-2.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:20 [crit] 30#30: *6 connect() to unix:/sockets/backend-1.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-1.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:25 [error] 30#30: *9 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:30 [error] 30#30: *10 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:35 [crit] 30#30: *11 connect() to unix:/sockets/backend-2.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-2.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:35 [crit] 30#30: *11 connect() to unix:/sockets/backend-1.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-1.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:40 [error] 30#30: *14 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:45 [error] 30#30: *15 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:50 [crit] 30#30: *16 connect() to unix:/sockets/backend-2.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-2.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:50 [crit] 30#30: *16 connect() to unix:/sockets/backend-1.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://unix:/sockets/backend-1.sock:/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:11:55 [error] 30#30: *19 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
nginx-1     | 2025/08/16 16:12:00 [error] 30#30: *20 no live upstreams while connecting to upstream, client: 172.20.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://api/payments-summary", host: "localhost:9999"
[Knginx-1 exited with code 0
[Kworker-1 exited with code 0
rinha-db-1  | 2025-08-16 16:12:05.784 UTC [1] LOG:  received fast shutdown request
nats-1      | [1] 2025/08/16 16:12:05.784960 [INF] Trapped "terminated" signal
nats-1      | [1] 2025/08/16 16:12:05.785117 [INF] Initiating Shutdown...
nats-1      | [1] 2025/08/16 16:12:05.785226 [INF] Server Exiting..
rinha-db-1  | 2025-08-16 16:12:05.788 UTC [1] LOG:  aborting any active transactions
rinha-db-1  | 2025-08-16 16:12:05.810 UTC [1] LOG:  background worker "logical replication launcher" (PID 96) exited with exit code 1
rinha-db-1  | 2025-08-16 16:12:05.811 UTC [91] LOG:  shutting down
rinha-db-1  | 2025-08-16 16:12:05.814 UTC [91] LOG:  checkpoint starting: shutdown immediate
rinha-db-1  | 2025-08-16 16:12:05.834 UTC [91] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.005 s, total=0.023 s; sync files=5, longest=0.003 s, average=0.001 s; distance=8 kB, estimate=8 kB; lsn=0/191CF80, redo lsn=0/191CF80
rinha-db-1  | 2025-08-16 16:12:05.841 UTC [1] LOG:  database system is shut down
[Knats-1 exited with code 0
