
 Network ricardo-santos_backend  Creating
 Network ricardo-santos_backend  Created
 Container app2  Creating
 Container app1  Creating
 Container app2  Created
 Container app1  Created
 Container backend-fight-nginx  Creating
 Container backend-fight-nginx  Created
Attaching to app1, app2, backend-fight-nginx
backend-fight-nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
backend-fight-nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
backend-fight-nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
backend-fight-nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
app2                 | "Connected to cluster!"
app2                 | 
app2                 | 03:04:14.067 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app1                 | "Connected to cluster!"
app1                 | 
app1                 | 03:04:14.672 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app2                 | 
app2                 | 03:04:15.353 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1418.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 03:04:15.354 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:04:20.364 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1419.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 03:04:20.365 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:04:25.375 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1420.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 03:04:25.375 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:04:30.385 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1423.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:04:30.386 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 03:04:35.396 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1421.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 03:04:35.397 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:04:40.406 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 03:04:40.407 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1422.0>): {:get_state, nil, nil}
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:04:45.417 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1427.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:04:45.418 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 03:04:50.428 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1429.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:04:50.428 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 03:04:55.438 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1431.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:04:55.439 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 03:05:00.452 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 03:05:00.453 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1423.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:05:05.464 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1424.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 03:05:05.465 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:05:10.475 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 03:05:10.476 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1425.0>): {:get_state, nil, nil}
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 03:05:15.485 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1436.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:05:15.486 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 03:05:20.496 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1438.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 03:05:20.496 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
[Kbackend-fight-nginx exited with code 0
app1                 | 
app1                 | 03:05:26.061 [notice] SIGTERM received - shutting down
app1                 | 
app2                 | 
app2                 | 03:05:26.065 [notice] SIGTERM received - shutting down
app2                 | 
[Kapp1 exited with code 0
[Kapp2 exited with code 0
