
 Network ricardo-santos_backend  Creating
 Network ricardo-santos_backend  Created
 Container app1  Creating
 Container app2  Creating
 Container app1  Created
 Container app2  Created
 Container backend-fight-nginx  Creating
 Container backend-fight-nginx  Created
Attaching to app1, app2, backend-fight-nginx
backend-fight-nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
backend-fight-nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
backend-fight-nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
backend-fight-nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
app2                 | "Connected to cluster!"
app2                 | 
app2                 | 23:03:33.059 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app1                 | "Connected to cluster!"
app1                 | 
app1                 | 23:03:33.702 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app2                 | 
app2                 | 23:03:34.371 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1418.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:03:34.372 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:03:39.382 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1419.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:03:39.383 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:03:44.392 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1422.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:03:44.393 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 23:03:49.405 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1420.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:03:49.406 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:03:54.419 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1421.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:03:54.419 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:03:59.430 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1426.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:03:59.430 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 23:04:04.440 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1428.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:04:04.441 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 23:04:09.450 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 23:04:09.451 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1422.0>): {:get_state, nil, nil}
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:04:14.461 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1423.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:04:14.462 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:04:19.472 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1432.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:04:19.472 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 23:04:24.484 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1434.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:04:24.484 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 23:04:29.494 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 | 23:04:29.495 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1424.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:04:34.505 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1425.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 23:04:34.506 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 23:04:39.516 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1438.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 23:04:39.517 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
[Kbackend-fight-nginx exited with code 0
app1                 | 
app1                 | 23:04:45.044 [notice] SIGTERM received - shutting down
app1                 | 
app2                 | 
app2                 | 23:04:45.046 [notice] SIGTERM received - shutting down
app2                 | 
[Kapp1 exited with code 0
[Kapp2 exited with code 0
