
 Network ricardo-santos_backend  Creating
 Network ricardo-santos_backend  Created
 Container app2  Creating
 Container app1  Creating
 Container app1  Created
 Container app2  Created
 Container backend-fight-nginx  Creating
 Container backend-fight-nginx  Created
Attaching to app1, app2, backend-fight-nginx
backend-fight-nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
backend-fight-nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
backend-fight-nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
backend-fight-nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
backend-fight-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
backend-fight-nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
app2                 | "Connected to cluster!"
app2                 | 
app2                 | 00:55:05.282 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app1                 | "Connected to cluster!"
app1                 | 
app1                 | 00:55:05.918 [info] Running PaymentDispatcher.Server with Bandit 1.7.0 at 0.0.0.0:9999 (http)
app2                 | 
app2                 | 00:55:06.448 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1418.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 00:55:06.449 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 00:55:11.459 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1421.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:11.460 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:55:16.470 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1419.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 00:55:16.470 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 00:55:21.481 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1424.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:21.482 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:55:26.492 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1420.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 00:55:26.492 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 00:55:31.502 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 00:55:31.503 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1421.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:36.512 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1428.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:36.513 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:55:41.523 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1430.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:41.524 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:55:46.534 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1422.0>): {:get_state, nil, nil}
app1                 | 
app1                 | 00:55:46.535 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 00:55:51.545 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 00:55:51.546 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<35588.1423.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:55:56.555 [error] GenServer PaymentDispatcher.StateManager terminating
app1                 | 
app1                 | 00:55:56.555 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app1                 |     ** (EXIT) an exception was raised:
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app1                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app1                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 | Last message (from #PID<35588.1424.0>): {:get_state, nil, nil}
app1                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app1                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app1                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app1                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app1                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app1                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app1                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app1                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app1                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app1                 | 
app2                 | 
app2                 | 00:56:01.565 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1435.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:56:01.566 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:56:06.576 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1437.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:56:06.576 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
app2                 | 
app2                 | 00:56:11.587 [error] GenServer PaymentDispatcher.StateManager terminating
app2                 | ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |     (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |     (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |     (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |     (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |     (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 | Last message (from #PID<0.1439.0>): {:get_state, nil, nil}
app2                 | 
app2                 | 00:56:11.588 [error] ** (exit) exited in: GenServer.call({:global, PaymentDispatcher.StateManager}, {:get_state, nil, nil}, :infinity)
app2                 |     ** (EXIT) an exception was raised:
app2                 |         ** (FunctionClauseError) no function clause matching in Calendar.ISO.parse_utc_datetime/2
app2                 |             (elixir 1.18.0) lib/calendar/iso.ex:591: Calendar.ISO.parse_utc_datetime(nil, :extended)
app2                 |             (elixir 1.18.0) lib/calendar/datetime.ex:1241: DateTime.from_iso8601/3
app2                 |             (payment_dispatcher 0.1.0) lib/payment_dispatcher/state_manager.ex:46: PaymentDispatcher.StateManager.handle_call/3
app2                 |             (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
app2                 |             (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
app2                 |             (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
app2                 |     (elixir 1.18.0) lib/gen_server.ex:1128: GenServer.call/3
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:26: anonymous fn/2 in PaymentDispatcher.Server.do_match/4
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in PaymentDispatcher.Server.dispatch/2
app2                 |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
app2                 |     (payment_dispatcher 0.1.0) deps/plug/lib/plug/router.ex:242: PaymentDispatcher.Server.dispatch/2
app2                 |     (payment_dispatcher 0.1.0) lib/server.ex:1: PaymentDispatcher.Server.plug_builder_call/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:131: Bandit.Pipeline.call_plug!/2
app2                 |     (bandit 1.7.0) lib/bandit/pipeline.ex:42: Bandit.Pipeline.run/5
app2                 | 
[Kbackend-fight-nginx exited with code 0
app2                 | 
app2                 | 00:56:17.188 [notice] SIGTERM received - shutting down
app2                 | 
app1                 | 
app1                 | 00:56:17.196 [notice] SIGTERM received - shutting down
app1                 | 
[Kapp1 exited with code 0
[Kapp2 exited with code 0
